### ISSUE TITLE
getPlaylistTracks with null user broken, used to work in 2.5.0

### ISSUE THREAD

**Issue by onkelsteffi** [thelinmichael/spotify-web-api-node#264]
Hi,
if i want o lookup this playlist:
https://open.spotify.com/playlist/2grQphfYbglcdPJZkFijg3

in 2.5.0 i used to get it lie this:
getPlaylistTracks(null, "2grQphfYbglcdPJZkFijg3", {
      offset: offset,
      limit: limit
    }).then ...

but this does not work anymore in 4.0, it just throws, and returns nothing, so i cant call "then"
[ERROR] md - uncaughtException:TypeError: callback is not a function
    at /home/md/checkout/server_nodejs/node_modules/spotify-web-api-node/src/http-manager.js:90:14
    at Request.callback (/home/md/checkout/server_nodejs/node_modules/superagent/lib/node/index.js:728:3)
    at parser (/home/md/checkout/server_nodejs/node_modules/superagent/lib/node/index.js:916:18)
    at Stream.res.on (/home/md/checkout/server_nodejs/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at Stream.emit (events.js:197:13)
    at Stream.EventEmitter.emit (domain.js:446:20)
    at Unzip.unzip.on (/home/md/checkout/server_nodejs/node_modules/superagent/lib/node/unzip.js:55:12)
    at Unzip.emit (events.js:202:15)
    at Unzip.EventEmitter.emit (domain.js:446:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

**Comment by kevinguebert** [comment]
I _think_ the documentation needs to be updated a bit for that. If you [look at the code](https://github.com/thelinmichael/spotify-web-api-node/blob/master/src/spotify-web-api.js#L501), the user parameter is no longer there in the request:
```
 getPlaylistTracks: function(playlistId, options, callback) {
...
```
Maybe try this and see if it works:
```
getPlaylistTracks("2grQphfYbglcdPJZkFijg3", {
offset: offset,
limit: limit
}).then ...
```

**Comment by onkelsteffi** [comment]
unfortunately not, results in a bad request.

 (node:18720) UnhandledPromiseRejectionWarning: Unhandled promise rejection
(rejection id: 1): WebapiError: Bad Request

**Comment by onkelsteffi** [comment]
sorry, possibly some mistake with my playlist id, now it works, thank you!
stephan

**Comment by kevinguebert** [comment]
Awesome good to hear! @thelinmichael this issue can be closed 🔥
